use crate::node::{InputType, InsightState, Node, NodeInput, NodeOutput, OutputType};

/// Retrieve all supported Built-In Engine components to dynamically render in visually connected tools (like Tauri Studio).
pub fn get_builtin_nodes() -> Vec<Node> {
    vec![
        Node {
            id: "builtin_add_event".to_string(),
            node_type: crate::node::NodeType::Trigger,
            label: "Add Event".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "on_start".to_string(),
                    input_type: InputType::OnStart,
                    value: None,
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "event_type".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("Bar")),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "timeframe_amount".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(15)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "timeframe_unit".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("Minute")),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "allow_trading".to_string(),
                    input_type: InputType::Bool,
                    value: Some(serde_json::json!(false)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![NodeOutput {
                name: "on_start".to_string(),
                output_type: OutputType::OnStart,
                insight_state: None,
            }],
            source_file: Some("add_event".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_test_entry".to_string(),
            node_type: crate::node::NodeType::Alpha,
            label: "test_entry".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "on_bar".to_string(),
                    input_type: InputType::OnBar,
                    value: None,
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "atr_period".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(14)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "limit_entries".to_string(),
                    input_type: InputType::Bool,
                    value: Some(serde_json::json!(false)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "max_spawn".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(1)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "base_confidence_modifier_field".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("")),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: None,
                },
                NodeOutput {
                    name: "alpha_result".to_string(),
                    output_type: OutputType::AlphaResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "alpha_instance".to_string(),
                    output_type: OutputType::AlphaInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("built_in_test_entry".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_insight_submit".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "insight_submit".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::New),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Executed),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("insight_submit".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_allow_trading_window".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "allow_trading_window".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "start".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("09:30")),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "end".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("16:00")),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "days".to_string(),
                    input_type: InputType::Array,
                    value: Some(serde_json::json!(["0", "1", "2", "3", "4"])),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("allow_trading_window".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_and_pipe".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "and_pipe".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "insights_pipes".to_string(),
                    input_type: InputType::InsightPipeInstance,
                    value: None,
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("and_pipe".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_or_pipe".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "or_pipe".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "insights_pipes".to_string(),
                    input_type: InputType::InsightPipeInstance,
                    value: None,
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("or_pipe".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_cancel_opposite".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "cancel_opposite".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::New),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("cancel_opposite".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_market_order_entry".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "market_order_entry".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::New),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("market_order_entry".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_insight_ttl_config".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "insight_ttl_config".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "period_unfilled".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(0)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "period_till_tp".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(0)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("insight_ttl_config".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_ema_price_crossover".to_string(),
            node_type: crate::node::NodeType::Alpha,
            label: "ema_price_crossover".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "on_bar".to_string(),
                    input_type: InputType::OnBar,
                    value: None,
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "atr_period".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(14)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "ema_period".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(14)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "base_confidence_modifier_field".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("")),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: None,
                },
                NodeOutput {
                    name: "alpha_result".to_string(),
                    output_type: OutputType::AlphaResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "alpha_instance".to_string(),
                    output_type: OutputType::AlphaInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("built_in_ema_price_crossover".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_rsi_divergance_alpha".to_string(),
            node_type: crate::node::NodeType::Alpha,
            label: "rsi_divergance_alpha".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "on_bar".to_string(),
                    input_type: InputType::OnBar,
                    value: None,
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "local_window".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(36)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "divergance_window".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(50)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "atr_period".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(14)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "rsi_period".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(14)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "base_confidence_modifier_field".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("")),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: None,
                },
                NodeOutput {
                    name: "alpha_result".to_string(),
                    output_type: OutputType::AlphaResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "alpha_instance".to_string(),
                    output_type: OutputType::AlphaInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("built_in_rsi_divergance_alpha".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_dynamic_quantity_to_risk".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "dynamic_quantity_to_risk".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "maximum_cost_basis".to_string(),
                    input_type: InputType::Float,
                    value: Some(serde_json::json!(200000.0)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "minimum_cost_basis".to_string(),
                    input_type: InputType::Float,
                    value: Some(serde_json::json!(1000.0)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("dynamic_quantity_to_risk".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_percentage_risk_to_quantity".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "percentage_risk_to_quantity".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "risk_percent".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(2)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("percentage_risk_to_quantity".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_full_account_quantity_to_risk".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "full_account_quantity_to_risk".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::New),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("full_account_quantity_to_risk".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_minimum_risk_to_reward".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "minimum_risk_to_reward".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "minimum_rr".to_string(),
                    input_type: InputType::Float,
                    value: Some(serde_json::json!(2.0)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("minimum_risk_to_reward".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_reject_expired_insight".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "reject_expired_insight".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::New),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Rejected),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("reject_expired_insight".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_percentage_dca_levels".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "percentage_dca_levels".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::New),
                },
                NodeInput {
                    name: "dca_percentage".to_string(),
                    input_type: InputType::Float,
                    value: Some(serde_json::json!(0.01)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "dca_levels".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(5)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::New),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("percentage_dca_levels".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_basic_stop_loss".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "basic_stop_loss".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::Filled),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Filled),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("basic_stop_loss".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_basic_take_profit".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "basic_take_profit".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::Filled),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Filled),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("basic_take_profit".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_scale_out".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "scale_out".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::Filled),
                },
                NodeInput {
                    name: "sell_off_percentage".to_string(),
                    input_type: InputType::Float,
                    value: Some(serde_json::json!(0.5)),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Filled),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("scale_out".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_close_market_changed".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "close_market_changed".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "insights".to_string(),
                input_type: InputType::Insights,
                value: None,
                is_public: true,
                insight_state: Some(InsightState::Filled),
            }],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Filled),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("close_market_changed".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_end_of_day_close".to_string(),
            node_type: crate::node::NodeType::Pipe,
            label: "end_of_day_close".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![
                NodeInput {
                    name: "insights".to_string(),
                    input_type: InputType::Insights,
                    value: None,
                    is_public: true,
                    insight_state: Some(InsightState::Filled),
                },
                NodeInput {
                    name: "minutes_before_end_of_day".to_string(),
                    input_type: InputType::Int,
                    value: Some(serde_json::json!(15)),
                    is_public: true,
                    insight_state: None,
                },
                NodeInput {
                    name: "end_of_day_time_utc".to_string(),
                    input_type: InputType::Str,
                    value: Some(serde_json::json!("23:45")),
                    is_public: true,
                    insight_state: None,
                },
            ],
            outputs: vec![
                NodeOutput {
                    name: "insights_out".to_string(),
                    output_type: OutputType::Insights,
                    insight_state: Some(InsightState::Filled),
                },
                NodeOutput {
                    name: "pipe_result".to_string(),
                    output_type: OutputType::InsightPipeResult,
                    insight_state: None,
                },
                NodeOutput {
                    name: "pipe_instance".to_string(),
                    output_type: OutputType::InsightPipeInstance,
                    insight_state: None,
                },
            ],
            source_file: Some("end_of_day_close".to_string()),
            lifecycle_phase: None,
            lifecycle_timing: None,
            can_fail: None,
            undeletable: false,
        },
        Node {
            id: "builtin_preseed_warmup_history".to_string(),
            node_type: crate::node::NodeType::LogicBlock,
            label: "preseed_warmup_history".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "init".to_string(),
                input_type: InputType::Init,
                value: None,
                is_public: true,
                insight_state: None,
            }],
            outputs: vec![NodeOutput {
                name: "init".to_string(),
                output_type: OutputType::Init,
                insight_state: None,
            }],
            source_file: Some("preseed_warmup_history".to_string()),
            lifecycle_phase: Some(crate::node::LifecyclePhase::OnInit),
            lifecycle_timing: Some(crate::node::LifecycleTiming::BeforeGenerated),
            can_fail: Some(false),
            undeletable: false,
        },
        Node {
            id: "builtin_close_all_filled_positions".to_string(),
            node_type: crate::node::NodeType::LogicBlock,
            label: "close_all_filled_positions".to_string(),
            x: 0.0,
            y: 0.0,
            inputs: vec![NodeInput {
                name: "on_teardown".to_string(),
                input_type: InputType::OnTeardown,
                value: None,
                is_public: true,
                insight_state: None,
            }],
            outputs: vec![NodeOutput {
                name: "on_teardown".to_string(),
                output_type: OutputType::OnTeardown,
                insight_state: None,
            }],
            source_file: Some("close_all_filled_positions".to_string()),
            lifecycle_phase: Some(crate::node::LifecyclePhase::OnTeardown),
            lifecycle_timing: Some(crate::node::LifecycleTiming::BeforeGenerated),
            can_fail: Some(true),
            undeletable: false,
        },
    ]
}
